module.exports = {
	"467b712f6f3dd1baad34f7b11b75f7d1": {
        typeOfMachine: "IpsoWasher_W10kg",
        machineName: "SP-W1",
        active: false,
        sent: false,
        locked: false,
        amountPaid: 0,
        totalPaid: 0,
        wechatPaid: 0,
        totalWechat: 0,
        totalManual: 0,
        coinPaid: 0,
        manualPaid: 0,
        totalCoin: 0,
        totalRun: 0,
        coldRun: 0,
        warmRun: 0,
        otherRun: 0,
        hotRun: 0,
        doneTime: 0,
        startTime: 0,
        totalTime: 0,
        oneRunTime: 25,
        lockCounter: 0,
        version: 0,
	}, 
	"e15ceae8fa62a160cebe0a1644e6116c": {
      	typeOfMachine: "detergent",
      	machineName: "SP-V1",
     	  active: false,
        locked: false,
     	  sent: false,
      	totalPaid: 0,
      	totalWechat: 0,
      	totalManual: 0,
      	totalCoin: 0,
      	detergent: 0,
      	beg: 0,
      	softnr: 0,
      	version: 0,
     },
  //   "ff667ad6aeec13ca9b39a69ab1b327d4": {
  //       typeOfMachine: "IpsoWasher_W10kg",
  //       machineName: "SP-W2",
  //       active: false,
  //       sent: false,
  //       locked: false,
  //       amountPaid: 0,
  //       totalPaid: 0,
  //       wechatPaid: 0,
  //       totalWechat: 0,
  //       totalManual: 0,
  //       coinPaid: 0,
  //       manualPaid: 0,
  //       totalCoin: 0,
  //       totalRun: 0,
  //       coldRun: 0,
  //       warmRun: 0,
  //       otherRun: 0,
  //       hotRun: 0,
  //       doneTime: 0,
  //       startTime: 0,
  //       totalTime: 0,
  //       oneRunTime: 25,
  //       lockCounter: 0,
  //       version: 0,
  //   },
  //   "afd3464a6b443af1ec65600881746d73": {
  //       typeOfMachine: "IpsoWasher_W10kg",
  //       machineName: "SP-W3",
  //       active: false,
  //       sent: false,
  //       locked: false,
  //       amountPaid: 0,
  //       totalPaid: 0,
  //       wechatPaid: 0,
  //       totalWechat: 0,
  //       totalManual: 0,
  //       coinPaid: 0,
  //       manualPaid: 0,
  //       totalCoin: 0,
  //       totalRun: 0,
  //       coldRun: 0,
  //       warmRun: 0,
  //       otherRun: 0,
  //       hotRun: 0,
  //       doneTime: 0,
  //       startTime: 0,
  //       totalTime: 0,
  //       oneRunTime: 25,
  //       lockCounter: 0,
  //       version: 0,
  //   },
  //   "f42adf7fc7c32612ff63fdd49fd7b88f": {
  //       typeOfMachine: "IpsoWasher_W14kg",
  //       machineName: "SP-W4",
  //       active: false,
  //       sent: false,
  //       locked: false,
  //       amountPaid: 0,
  //       totalPaid: 0,
  //       wechatPaid: 0,
  //       totalWechat: 0,
  //       totalManual: 0,
  //       coinPaid: 0,
  //       manualPaid: 0,
  //       totalCoin: 0,
  //       totalRun: 0,
  //       coldRun: 0,
  //       warmRun: 0,
  //       otherRun: 0,
  //       hotRun: 0,
  //       doneTime: 0,
  //       startTime: 0,
  //       totalTime: 0,
  //       oneRunTime: 25,
  //       lockCounter: 0,
  //       version: 0,
  //   },
  //   "2229d9eb2ec89ca584c408c17d373a4e": {
  //       typeOfMachine: "IpsoWasher_W14kg",
  //       machineName: "SP-W5",
  //       active: false,
  //       sent: false,
  //       locked: false,
  //       amountPaid: 0,
  //       totalPaid: 0,
  //       wechatPaid: 0,
  //       totalWechat: 0,
  //       totalManual: 0,
  //       coinPaid: 0,
  //       manualPaid: 0,
  //       totalCoin: 0,
  //       totalRun: 0,
  //       coldRun: 0,
  //       warmRun: 0,
  //       otherRun: 0,
  //       hotRun: 0,
  //       doneTime: 0,
  //       startTime: 0,
  //       totalTime: 0,
  //       oneRunTime: 25,
  //       lockCounter: 0,
  //       version: 0,
  //   },
  //   "7efdcee9e6e98cf340a5253bd60ef6e7": {
  //       typeOfMachine: "IpsoWasher_W14kg",
  //       machineName: "SP-W6",
  //       active: false,
  //       sent: false,
  //       locked: false,
  //       amountPaid: 0,
  //       totalPaid: 0,
  //       wechatPaid: 0,
  //       totalWechat: 0,
  //       totalManual: 0,
  //       coinPaid: 0,
  //       manualPaid: 0,
  //       totalCoin: 0,
  //       totalRun: 0,
  //       coldRun: 0,
  //       warmRun: 0,
  //       otherRun: 0,
  //       hotRun: 0,
  //       doneTime: 0,
  //       startTime: 0,
  //       totalTime: 0,
  //       oneRunTime: 25,
  //       lockCounter: 0,
  //       version: 0,
  //   },
  //   "fdfe402564827b4a60a8f282d3263a25": {
  //       typeOfMachine: "IpsoWasher_W14kg",
  //       machineName: "SP-W7",
  //       active: false,
  //       sent: false,
  //       locked: false,
  //       amountPaid: 0,
  //       totalPaid: 0,
  //       wechatPaid: 0,
  //       totalWechat: 0,
  //       totalManual: 0,
  //       coinPaid: 0,
  //       manualPaid: 0,
  //       totalCoin: 0,
  //       totalRun: 0,
  //       coldRun: 0,
  //       warmRun: 0,
  //       otherRun: 0,
  //       hotRun: 0,
  //       doneTime: 0,
  //       startTime: 0,
  //       totalTime: 0,
  //       oneRunTime: 25,
  //       lockCounter: 0,
  //       version: 0,
  //   },
  //   "feef20730ddd89537eafacf35e19e89f": {
  //       typeOfMachine: "IpsoWasher_W14kg",
  //       machineName: "SP-W8",
  //       active: false,
  //       sent: false,
  //       locked: false,
  //       amountPaid: 0,
  //       totalPaid: 0,
  //       wechatPaid: 0,
  //       totalWechat: 0,
  //       totalManual: 0,
  //       coinPaid: 0,
  //       manualPaid: 0,
  //       totalCoin: 0,
  //       totalRun: 0,
  //       coldRun: 0,
  //       warmRun: 0,
  //       otherRun: 0,
  //       hotRun: 0,
  //       doneTime: 0,
  //       startTime: 0,
  //       totalTime: 0,
  //       oneRunTime: 25,
  //       lockCounter: 0,
  //       version: 0,
  //   },
  //   "eec774d2310b93539f09733eaefb2504": {
  //       typeOfMachine: "IpsoWasher_W14kg",
  //       machineName: "SP-W9",
  //       active: false,
  //       sent: false,
  //       locked: false,
  //       amountPaid: 0,
  //       totalPaid: 0,
  //       wechatPaid: 0,
  //       totalWechat: 0,
  //       totalManual: 0,
  //       coinPaid: 0,
  //       manualPaid: 0,
  //       totalCoin: 0,
  //       totalRun: 0,
  //       coldRun: 0,
  //       warmRun: 0,
  //       otherRun: 0,
  //       hotRun: 0,
  //       doneTime: 0,
  //       startTime: 0,
  //       totalTime: 0,
  //       oneRunTime: 25,
  //       lockCounter: 0,
  //       version: 0,
  //   },
  //   "377f26e90bfc172558507ac4a145d950": {
  //       typeOfMachine: "IpsoWasher_W14kg",
  //       machineName: "SP-W10",
  //       active: false,
  //       sent: false,
  //       locked: false,
  //       amountPaid: 0,
  //       totalPaid: 0,
  //       wechatPaid: 0,
  //       totalWechat: 0,
  //       totalManual: 0,
  //       coinPaid: 0,
  //       manualPaid: 0,
  //       totalCoin: 0,
  //       totalRun: 0,
  //       coldRun: 0,
  //       warmRun: 0,
  //       otherRun: 0,
  //       hotRun: 0,
  //       doneTime: 0,
  //       startTime: 0,
  //       totalTime: 0,
  //       oneRunTime: 25,
  //       lockCounter: 0,
  //       version: 0,
  //   },
  //   "7cb386904331bb094939f84e628a6359": {
  //       typeOfMachine: "IpsoWasher_W14kg",
  //       machineName: "SP-W11",
  //       active: false,
  //       sent: false,
  //       locked: false,
  //       amountPaid: 0,
  //       totalPaid: 0,
  //       wechatPaid: 0,
  //       totalWechat: 0,
  //       totalManual: 0,
  //       coinPaid: 0,
  //       manualPaid: 0,
  //       totalCoin: 0,
  //       totalRun: 0,
  //       coldRun: 0,
  //       warmRun: 0,
  //       otherRun: 0,
  //       hotRun: 0,
  //       doneTime: 0,
  //       startTime: 0,
  //       totalTime: 0,
  //       oneRunTime: 25,
  //       lockCounter: 0,
  //       version: 0,
  //   },
  //   "04680fafa7e54799527afe1bb95e5dd6": {
  //       typeOfMachine: "IpsoWasher_W25kg",
  //       machineName: "SP-W12",
  //       active: false,
  //       sent: false,
  //       locked: false,
  //       amountPaid: 0,
  //       totalPaid: 0,
  //       wechatPaid: 0,
  //       totalWechat: 0,
  //       totalManual: 0,
  //       coinPaid: 0,
  //       manualPaid: 0,
  //       totalCoin: 0,
  //       totalRun: 0,
  //       coldRun: 0,
  //       warmRun: 0,
  //       otherRun: 0,
  //       hotRun: 0,
  //       doneTime: 0,
  //       startTime: 0,
  //       totalTime: 0,
  //       oneRunTime: 25,
  //       lockCounter: 0,
  //       version: 0,
  //   },
  //   "e338a1d0f3e6cad1c83a086a597b4e3d": {
  //       typeOfMachine: "IpsoWasher_W25kg",
  //       machineName: "SP-W13",
  //       active: false,
  //       sent: false,
  //       locked: false,
  //       amountPaid: 0,
  //       totalPaid: 0,
  //       wechatPaid: 0,
  //       totalWechat: 0,
  //       totalManual: 0,
  //       coinPaid: 0,
  //       manualPaid: 0,
  //       totalCoin: 0,
  //       totalRun: 0,
  //       coldRun: 0,
  //       warmRun: 0,
  //       otherRun: 0,
  //       hotRun: 0,
  //       doneTime: 0,
  //       startTime: 0,
  //       totalTime: 0,
  //       oneRunTime: 25,
  //       lockCounter: 0,
  //       version: 0,
  //   },
  //   "da8cc37a4700369f998e320d0ba8a5ff": {
  //       typeOfMachine: "IpsoWasher_W25kg",
  //       machineName: "SP-W14",
  //       active: false,
  //       sent: false,
  //       locked: false,
  //       amountPaid: 0,
  //       totalPaid: 0,
  //       wechatPaid: 0,
  //       totalWechat: 0,
  //       totalManual: 0,
  //       coinPaid: 0,
  //       manualPaid: 0,
  //       totalCoin: 0,
  //       totalRun: 0,
  //       coldRun: 0,
  //       warmRun: 0,
  //       otherRun: 0,
  //       hotRun: 0,
  //       doneTime: 0,
  //       startTime: 0,
  //       totalTime: 0,
  //       oneRunTime: 25,
  //       lockCounter: 0,
  //       version: 0,
  //   },
	 // "920e0e55fcdd67b9384e0b2bf8096c9d": {
	 // 	typeOfMachine: "dex_dryer_double_D25kg",
	 // 	machineName: "SP-D15-16",
	 // 	active: false,
	 // 	sent: false,
	 // 	locked: {
	 // 		upper: false,
	 // 		lower: false
	 // 	},
	 // 	amountPaid: 0,
	 // 	totalPaid: 0,
	 // 	wechatPaid: 0,
	 // 	totalWechat: 0,
	 // 	coinPaid: 0,
	 // 	totalCoin: 0,
	 // 	totalRun: 0,
	 // 	doneTime: {
	 // 		upper: 0,
	 // 		lower: 0
	 // 	},
	 // 	startTime: {
	 // 		upper: 0,
	 // 		lower: 0
	 // 	},
	 // 	totalTime: {
	 // 		upper: 0,
	 // 		lower: 0
	 // 	},
	 // 	lockCounter: {
	 // 		upper: 0,
	 // 		lower: 0
	 // 	},
	 // 	version: 0,
	 // 	oneRunTime: 3
	 // },
	 "ae7d7950ed68a29b627719c0723f0ca0": {
	 	typeOfMachine: "dex_dryer_double_D25kg",
	 	machineName: "SP-D17-18",
	 	active: false,
	 	sent: false,
	 	locked: {
	 		upper: false,
	 		lower: false
	 	},
	 	amountPaid: 0,
	 	totalPaid: 0,
	 	wechatPaid: 0,
	 	totalWechat: 0,
	 	coinPaid: 0,
	 	totalCoin: 0,
	 	totalRun: 0,
	 	doneTime: {
	 		upper: 0,
	 		lower: 0
	 	},
    rcvTime: {
      upper: 0,
      lower: 0
    },
	 	startTime: {
	 		upper: 0,
	 		lower: 0
	 	},
	 	totalTime: {
	 		upper: 0,
	 		lower: 0
	 	},
	 	lockCounter: {
	 		upper: 0,
	 		lower: 0
	 	},
	 	version: 0,
	 	oneRunTime: 3
	 },
	 "b036287a0b987f47adb972a5c487a9d5": {
	 	typeOfMachine: "dex_dryer_double_D14kg",
	 	machineName: "SP-D19-20",
	 	active: false,
	 	sent: false,
	 	locked: {
	 		upper: false,
	 		lower: false
	 	},
	 	amountPaid: 0,
	 	totalPaid: 0,
	 	wechatPaid: 0,
	 	totalWechat: 0,
	 	coinPaid: 0,
	 	totalCoin: 0,
	 	totalRun: 0,
	 	doneTime: {
	 		upper: 0,
	 		lower: 0
	 	},
    rcvTime: {
      upper: 0,
      lower: 0
    },
	 	startTime: {
	 		upper: 0,
	 		lower: 0
	 	},
	 	totalTime: {
	 		upper: 0,
	 		lower: 0
	 	},
	 	lockCounter: {
	 		upper: 0,
	 		lower: 0
	 	},
	 	version: 0,
	 	oneRunTime: 3
	 }, 
	"eacd155d4cf3a996cfd92de5e623fffa": {
              typeOfMachine: "dex_dryer_D14kg",
              machineName: "SP-D5",
              active: false,
              sent: false,
              locked: false,
              amountPaid: 0,
              totalPaid: 0,
              wechatPaid: 0,
              totalWechat: 0,
              totalManual: 0,
              coinPaid: 0,
              manualPaid: 0,
              totalCoin: 0,
              totalRun: 0,
              doneTime: 0,
              startTime: 0,
              totalTime: 0,
              oneRunTime: 5,
              lockCounter: 0,
              version: 0,
         }
	 // "2589002d3b606097b7c0b911bb4c2e3a": {
	 // 	typeOfMachine: "dex_dryer_double_D14kg",
	 // 	machineName: "SP-D21-22",
	 // 	active: false,
	 // 	sent: false,
	 // 	locked: {
	 // 		upper: false,
	 // 		lower: false
	 // 	},
	 // 	amountPaid: 0,
	 // 	totalPaid: 0,
	 // 	wechatPaid: 0,
	 // 	totalWechat: 0,
	 // 	coinPaid: 0,
	 // 	totalCoin: 0,
	 // 	totalRun: 0,
	 // 	doneTime: {
	 // 		upper: 0,
	 // 		lower: 0
	 // 	},
	 // 	startTime: {
	 // 		upper: 0,
	 // 		lower: 0
	 // 	},
	 // 	totalTime: {
	 // 		upper: 0,
	 // 		lower: 0
	 // 	},
	 // 	lockCounter: {
	 // 		upper: 0,
	 // 		lower: 0
	 // 	},
	 // 	version: 0,
	 // 	oneRunTime: 3
	 // },
	 // "c370953038cd99f11ac20a0103f51367": {
	 // 	typeOfMachine: "dex_dryer_double_D14kg",
	 // 	machineName: "SP-D23-24",
	 // 	active: false,
	 // 	sent: false,
	 // 	locked: {
	 // 		upper: false,
	 // 		lower: false
	 // 	},
	 // 	amountPaid: 0,
	 // 	totalPaid: 0,
	 // 	wechatPaid: 0,
	 // 	totalWechat: 0,
	 // 	coinPaid: 0,
	 // 	totalCoin: 0,
	 // 	totalRun: 0,
	 // 	doneTime: {
	 // 		upper: 0,
	 // 		lower: 0
	 // 	},
	 // 	startTime: {
	 // 		upper: 0,
	 // 		lower: 0
	 // 	},
	 // 	totalTime: {
	 // 		upper: 0,
	 // 		lower: 0
	 // 	},
	 // 	lockCounter: {
	 // 		upper: 0,
	 // 		lower: 0
	 // 	},
	 // 	version: 0,
	 // 	oneRunTime: 3
	 // },
	 // "ef89c66d748353f822e19506e1208537": {
	 // 	typeOfMachine: "dex_dryer_double_D14kg",
	 // 	machineName: "SP-D25-26",
	 // 	active: false,
	 // 	sent: false,
	 // 	locked: {
	 // 		upper: false,
	 // 		lower: false
	 // 	},
	 // 	amountPaid: 0,
	 // 	totalPaid: 0,
	 // 	wechatPaid: 0,
	 // 	totalWechat: 0,
	 // 	coinPaid: 0,
	 // 	totalCoin: 0,
	 // 	totalRun: 0,
	 // 	doneTime: {
	 // 		upper: 0,
	 // 		lower: 0
	 // 	},
	 // 	startTime: {
	 // 		upper: 0,
	 // 		lower: 0
	 // 	},
	 // 	totalTime: {
	 // 		upper: 0,
	 // 		lower: 0
	 // 	},
	 // 	lockCounter: {
	 // 		upper: 0,
	 // 		lower: 0
	 // 	},
	 // 	version: 0,
	 // 	oneRunTime: 3
	  //}
}
